Add missing header bootlegged by Boost < 1.72
In file included from src/core/audio/Stream.cpp:37:
src/core/audio/Stream.h:78:26: error: no template named 'deque' in namespace 'std'
            typedef std::deque<Buffer*> BufferList;
                    ~~~~~^
src/core/audio/Stream.cpp:75:25: error: invalid range expression of type 'int'; no viable 'begin'
      function available
    for (Buffer* buffer : this->recycledBuffers) {
                        ^ ~~~~
src/core/audio/Stream.cpp:79:25: error: invalid range expression of type 'int'; no viable 'begin'
      function available
    for (Buffer* buffer : this->filledBuffers) {
                        ^ ~~~~
src/core/audio/Stream.cpp:98:38: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        auto it = this->filledBuffers.begin();
                  ~~~~~~~~~~~~~~~~~~~^~~~~~
src/core/audio/Stream.cpp:99:41: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        while (it != this->filledBuffers.end()) {
                     ~~~~~~~~~~~~~~~~~~~^~~~
src/core/audio/Stream.cpp:100:34: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
            this->recycledBuffers.push_back(*it);
            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/core/audio/Stream.cpp:104:28: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        this->filledBuffers.clear();
        ~~~~~~~~~~~~~~~~~~~^~~~~~
src/core/audio/Stream.cpp:150:26: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
    this->recycledBuffers.push_back(buffer);
    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/core/audio/Stream.cpp:174:34: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
            this->recycledBuffers.push_back(buffer);
            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/core/audio/Stream.cpp:183:24: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
    if (recycledBuffers.size()) {
        ~~~~~~~~~~~~~~~^~~~~
src/core/audio/Stream.cpp:184:41: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        Buffer* target = recycledBuffers.front();
                         ~~~~~~~~~~~~~~~^~~~~~
src/core/audio/Stream.cpp:185:24: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        recycledBuffers.pop_front();
        ~~~~~~~~~~~~~~~^~~~~~~~~~
src/core/audio/Stream.cpp:195:28: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
    if (this->filledBuffers.size()) {
        ~~~~~~~~~~~~~~~~~~~^~~~~
src/core/audio/Stream.cpp:196:45: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        Buffer* buffer = this->filledBuffers.front();
                         ~~~~~~~~~~~~~~~~~~~^~~~~~
src/core/audio/Stream.cpp:197:28: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
        this->filledBuffers.pop_front();
        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
src/core/audio/Stream.cpp:210:41: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
    int recycled = this->recycledBuffers.size();
                   ~~~~~~~~~~~~~~~~~~~~~^~~~~
src/core/audio/Stream.cpp:267:26: error: member reference base type
      'musik::core::audio::Stream::BufferList' (aka 'int') is not a structure or union
            filledBuffers.push_back(target);
            ~~~~~~~~~~~~~^~~~~~~~~~