Fix build on systems with split ncurses/tinfo
On systems where ncurses is built with --with-termlib, libtinfo is a
separate library.

Building musikcube on such a system would fail with:

  ld: CMakeFiles/musikcube.dir/cursespp/App.cpp.o: undefined reference to symbol 'keypad'
  ld: /lib64/libtinfow.so.6: error adding symbols: DSO missing from command line

Using pkgconfig to look up the required link libraries resolves the issue.